server:
    port: ${PORT:8080}

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/joro?currentSchema=inventory
        username: inventory_app_usr
        password: prayer&
    devtools:
        restart:
            poll-interval: 2s
            quiet-period: 1s
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        open-in-view: false
    mustache:
        check-template-location: false
    sql:
        init:
            mode: always
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

vaadin:
    launch-browser: true
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,org.joro

logging:
    level:
        org:
            atmosphere: warn
